# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98101464f8ff5362f0367daca02bf38bbb5b9b7e67e663014bec3e8c2fed78b2e72c311a01053ba51a1bac3ba08377b6461fe649720d301b4ef59c50d6096408

test:
  secret_key_base: 190e890d606f529a8b39ecbc701b712303bc1f8530b928100f2965e62640ea45ca18b2a691ff5cccba8366be887c8a63eaf68ce53c166a9bfa42003e080c2ec5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
